name = "default"

[variants.light]
color0 = "#151515"
color1 = "#ac4142"
color2 = "#90a959"
color3 = "#f4bf75"
color4 = "#6a9fb5"
color5 = "#aa759f"
color6 = "#75b5aa"
color7 = "#d0d0d0"
color8 = "#505050"
color9 = "#ac4142"
color10 = "#90a959"
color11 = "#f4bf75"
color12 = "#6a9fb5"
color13 = "#aa759f"
color14 = "#75b5aa"
color15 = "#f5f5f5"
foreground = "#303030"
background = "#f5f5f5"
cursor_color = "#303030"

[variants.dark]
color0 = "#151515"
color1 = "#ac4142"
color2 = "#90a959"
color3 = "#f4bf75"
color4 = "#6a9fb5"
color5 = "#aa759f"
color6 = "#75b5aa"
color7 = "#d0d0d0"
color8 = "#505050"
color9 = "#ac4142"
color10 = "#90a959"
color11 = "#f4bf75"
color12 = "#6a9fb5"
color13 = "#aa759f"
color14 = "#75b5aa"
color15 = "#f5f5f5"
foreground = "#d0d0d0"
background = "#151515"
cursor_color = "#d0d0d0"
