[[themes]]
name = "example"

[themes.variants.light]
lv00 = "#e6e6e6"
lv01 = "#cecece"
lv02 = "#919191"
lv03 = "#6e6e6e"
lv04 = "#3e3e3e"
lv05 = "#232323"
clrd = "#8a2f3a"
clor = "#804a1f"
clyl = "#8a6a2a"
clgn = "#4f7b2b"
clcy = "#277e89"
clbl = "#2369a2"
clmg = "#753a92"
clbn = "#6b241c"

[themes.variants.dark]
lv00 = "#121212"
lv01 = "#232323"
lv02 = "#3e3e3e"
lv03 = "#6e6e6e"
lv04 = "#919191"
lv05 = "#cecece"
clrd = "#e06c75"
clor = "#d19a66"
clyl = "#e5c07b"
clgn = "#98c379"
clcy = "#56b6c2"
clbl = "#61afef"
clmg = "#c678dd"
clbn = "#be5046"
