[[themes]]
name = "example"

[themes.syntax]
string = "base0E"
function = "base0A"
keyword = "base0D"
comment = "base0F"
type = "base08"
constant = "base0C"
identifier = "base0B"

[themes.variants.light]
base00 = "#e6e6e6"
base01 = "#cecece"
base02 = "#919191"
base03 = "#6e6e6e"
base04 = "#3e3e3e"
base05 = "#232323"
base06 = "#121212"
base07 = "#636dAc"
base08 = "#8a2f3a"
base09 = "#804a1f"
base0A = "#8a6a2a"
base0B = "#4f7b2b"
base0C = "#277e89"
base0D = "#2369a2"
base0E = "#753a92"
base0F = "#6b241c"

[themes.variants.dark]
base00 = "#121212"
base01 = "#232323"
base02 = "#3e3e3e"
base03 = "#6e6e6e"
base04 = "#919191"
base05 = "#cecece"
base06 = "#e6e6e6"
base07 = "#cdd6f4"
base08 = "#e06c75"
base09 = "#d19a66"
base0A = "#e5c07b"
base0B = "#98c379"
base0C = "#56b6c2"
base0D = "#61afef"
base0E = "#c678dd"
base0F = "#be5046"
