[[themes]]
name = "example"

[themes.syntax]
# string = "purple"
# function = "yellow"
# keyword = "blue"
# comment = "brown"
# type = "red"
# constant = "cyan"
# identifier = "green"

[themes.ui]
# cursor = "red"
# cursor_line = "cyan"

[themes.variants.light]
background = "#e6e6e6"
background_alt = "#cecece"
background_selection = "#919191"
foreground_invisible = "#6e6e6e"
foreground_dark = "#3e3e3e"
foreground = "#232323"
red = "#8a2f3a"
orange = "#804a1f"
yellow = "#8a6a2a"
green = "#4f7b2b"
cyan = "#277e89"
blue = "#2369a2"
purple = "#753a92"
brown = "#6b241c"

[themes.variants.dark]
background = "#121212"
background_alt = "#232323"
background_selection = "#3e3e3e"
foreground_invisible = "#6e6e6e"
foreground_dark = "#919191"
foreground = "#cecece"
red = "#e06c75"
orange = "#d19a66"
yellow = "#e5c07b"
green = "#98c379"
cyan = "#56b6c2"
blue = "#61afef"
purple = "#c678dd"
brown = "#be5046"
