[[themes]]
name = "example"

[themes.variants.light]
lv00 = "#F7F7F7"
lv01 = "#E4E4E4"
lv02 = "#C8C8C8"
lv03 = "#A0A0A0"
lv04 = "#707070"
lv05 = "#303030"
clrd = "#C4473D"
clor = "#B5671D"
clyl = "#B29A00"
clgn = "#3C8C4D"
clcy = "#2B8C86"
clbl = "#3663AA"
clmg = "#8A5A86"
clbn = "#6E4C47"

[themes.variants.dark]
lv00 = "#0A0A0A"
lv01 = "#1A1A1A"
lv02 = "#2A2A2A"
lv03 = "#4A4A4A"
lv04 = "#7A7A7A"
lv05 = "#C1C1C1"
clrd = "#FF5C57"
clor = "#FF9F43"
clyl = "#FFD93B"
clgn = "#5CC26C"
clcy = "#3FD1C7"
clbl = "#4D8EDA"
clmg = "#C586C0"
clbn = "#A9746E"
